### ISSUE TITLE
Display settings are crashing - part 2

### ISSUE THREAD

**Issue by QuinceROMs** [PixelOS-Pixelish/packages_apps_Settings#23]
Four new refresh rate selector commits (here and in the frameworks_base) cause display settings to crash. I compiled an unofficial build for OnePlus 7 (guacamoleb), where the refresh rate is 60Hz. After manually undoing them, the display settings work correctly. I am attaching a link to the log: https://logpaste.com/NJL7WXYa

https://github.com/PixelOS-AOSP/packages_apps_Settings/commit/5cce1d962deaccd4ae880a9b221f2e9afe83ed49
https://github.com/PixelOS-AOSP/packages_apps_Settings/commit/1c34b7aad1a8972ddc2829b11075640942559609
https://github.com/PixelOS-AOSP/packages_apps_Settings/commit/dc75302f1bfd114b7614fca25154b46ca60faa53

**Comment by whyredfire** [comment]
Fixed after https://github.com/PixelOS-AOSP/packages_apps_Settings/commit/9717a39fc01ee4718537fc7697e227897df98d38.

Thanks!
